apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
  - name: app
    image: arungupta/print-hello:latest
    env:
    - name: COUNT
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: COUNT
    ports:
    - containerPort: 8080
