apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-deployment 
spec:
  replicas: 3 
  template:
    metadata:
      labels:
        app: demo-app 
    spec:
      containers:
      - name: echoheaders 
        image: gcr.io/google_containers/echoserver:1.4
        imagePullPolicy: IfNotPresent 
        ports: 
        - containerPort: 8080
          hostPort: 8080