apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: DemoApp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3030
  - name: https
    protocol: TCP
    port: 443
    targetPort: 3031