apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-v1
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - name: app-v1
        image: arungupta/app-upgrade:v1
        ports:
        - containerPort: 8080
